CREATE TABLE Room (
 id VARCHAR(6) PRIMARY KEY,
 code VARCHAR(6) UNIQUE NOT NULL,
 name VARCHAR(80) NOT NULL,
 description TEXT NULL,
 capacity INT NULL,
 owners TEXT NOT NULL, -- `simple-array` viene mappato come TEXT in TypeORM
 floor INT NULL,
 enabled BOOLEAN NOT NULL,
 locationId VARCHAR(6) NOT NULL,
 createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 createdBy VARCHAR(255) NULL,
 modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 modifiedBy VARCHAR(255) NULL,
 FOREIGN KEY (locationId) REFERENCES Location(id)
 );
