import {ALIGN_OPTIONS, ColumnModel, TYPE_OPTIONS} from '../../../core/model/column.model';
import {faEdit, faEye, faTrash} from '@fortawesome/free-solid-svg-icons';

export const displayedColumns: ColumnModel[] = [
  {
    key: 'id',
    name: '#',
    hide: false,
    type: TYPE_OPTIONS.ID,
    align: ALIGN_OPTIONS.CENTER,
    isFilterable: false,
    isSortable: false,
    className: 'text-slate-400 max-w-28 w-28',
    isExportable: true,
  },
  {
    key: 'name',
    name: 'Argomento',
    hide: false,
    type: TYPE_OPTIONS.COLOR,
    isFilterable: false,
    isSortable: true,
    isExportable: true,
  },
  {
    key: 'VIEW_KEYWORDS_COUNT',
    name: 'Keywords',
    hide: false,
    type: TYPE_OPTIONS.NUMBER,
    align: ALIGN_OPTIONS.CENTER,
    isFilterable: false,
    isSortable: true,
    isExportable: true,
  },
  {
    key: 'view',
    name: 'Dettaglio',
    hide: false,
    type: TYPE_OPTIONS.ICON,
    isFilterable: false,
    isSortable: false,
    align: ALIGN_OPTIONS.CENTER,
    stickyEnd: true,
    icon: faEye,
    isExportable: false,
  },
  {
    key: 'edit',
    name: 'Modifica',
    hide: false,
    type: TYPE_OPTIONS.ICON,
    isFilterable: false,
    isSortable: false,
    align: ALIGN_OPTIONS.CENTER,
    stickyEnd: true,
    icon: faEdit,
    isExportable: false,
  },
  {
    key: 'delete',
    name: 'Elimina',
    hide: false,
    type: TYPE_OPTIONS.ICON,
    isFilterable: false,
    isSortable: false,
    align: ALIGN_OPTIONS.CENTER,
    stickyEnd: true,
    icon: faTrash,
    isExportable: false,
  }
];
